In [40]:
import string
string.digits

'0123456789'

In [41]:
import string as s
s.digits

'0123456789'

In [42]:
from string import digits
print(digits)
print(punctuation)

0123456789


NameError: name 'punctuation' is not defined

In [43]:
#user defined has more priority than built in 
list1=[1,2,3,4,5]
sum=0
for i in list1:
    sum+=i
print(sum)


15


In [44]:
sum(list1)
#we see that sum though it is a built in function it was created by the user as an object.

TypeError: 'int' object is not callable

In [45]:
# import * implies to use every built in method in module


In [46]:
#user defined modules
import mod
mod.wish('Sathvik')


Iam  Sathvik


In [47]:
def area(r):
    import math
    a=3.14*math.pow(r,2)
    return a

In [48]:
area(7)

153.86

In [49]:
from statistics import mean
list1=[1,2,3,4,5]
mean(list1)

3

In [50]:
import statistics as s
list1=list(range(1,21))

In [51]:
s.mean(list1)

10.5

In [52]:
li=[1,1,2,2,2,2,3,3,3,3]
s.mode(li)

StatisticsError: no unique mode; found 2 equally common values

In [53]:
li=[1,1,2,2,2,2,3,3,3]
s.mode(li)

2

In [54]:
#standard deviation
s.stdev(li)

0.7817359599705717

In [55]:
s.variance(li)

0.6111111111111112

In [56]:
import random
print(random.randint(1,10))
print(random.randrange(1,10))
li=['hey','hello','who']
print(random.choice(li))
print(random.random())
print(random.choices(li,k=3))


6
5
hey
0.5117869060316714
['hello', 'hey', 'who']


In [57]:
s

<module 'statistics' from 'C:\\Users\\SathvikAN\\anaconda3\\lib\\statistics.py'>

In [58]:
str

str

In [60]:
#os module
#rename
#remove
#mkdir
#get
#chdir
#listdir
#rmdir
#getcwd

In [61]:
import os
os.mkdir('sample')


In [62]:
os.getcwd()

'C:\\Users\\SathvikAN\\AI&ML\\3 June'

In [63]:
os.listdir()

['.ipynb_checkpoints', '3 June 2020.ipynb', 'mod.py', 'sample', '__pycache__']

In [64]:
# chdir syntax is os.chdir('directory link')

In [65]:
os.rmdir('sample')

In [66]:
#numpy
import numpy as np
li=[1,2,3,4,5]
arr1=np.array(li)

In [67]:
arr1

array([1, 2, 3, 4, 5])

In [68]:
arr2=np.arange(11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
#diff b/w lists and numpy array
# numpy array occupy less memory
# numpy array are fast
# numpy array are more convinient


In [70]:
#less memory
import sys
size=100
li=list(range(size))
print(sys.getsizeof(li[0])*size)
arr3=np.arange(100)
print(arr3.itemsize*arr3.size)

2400
400


In [73]:
#fast
import time
l1=[1,2,3,4,5]
l2=[11,12,13,14,15]
start=time.time()
res=[x+y for x,y in zip(l1,l2)]
print(res)
print(time.time()-start)


[12, 14, 16, 18, 20]
0.000997781753540039


In [39]:
ar1=np.array(l1)
ar2=np.array(l2)
start=time.time()
print(ar1+ar2)
print(time.time()-start)

[12 14 16 18 20]
0.0009951591491699219
