In [2]:
#1 dimensional array
import numpy as np
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [5]:
#2 dimensional 
a1=np.array([[1,2,3],[4,5,6]])

In [6]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#to know dimensions of an array
a1.ndim

2

In [10]:
# to know no of rows and columsn in array
a1.shape

(2, 3)

In [11]:
#to know no of rows
a1.shape[0] # here 0 implies no of rows denotion

2

In [12]:
a1.shape[1] # here 1 implies no of columns denotion

3

In [23]:
a2=np.array([],dtype='int32')
a2=np.append(a2,int(input()))

12


In [25]:
a2=np.append(a2,[1,2,3,4,5])
a2

array([12,  1,  2,  3,  4,  5])

In [26]:
#slicing
a4=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a4[2]

array([7, 8, 9])

In [29]:
#indexing
a4[1,2]

6

In [30]:
a4[2:,0:2]

array([[7, 8]])

In [36]:
a4[0::2,]

array([[1, 2, 3],
       [7, 8, 9]])

In [38]:
#iterate through array
for i in a4:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [40]:
for j in a4.flat:
    print(j)

1
2
3
4
5
6
7
8
9


In [45]:
a5=np.arange(1,21).reshape(5,4)

In [46]:
a5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [47]:
res=(a5%2==0)
res
#it returns boolean 

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [49]:
#to neglect false values and get our result
a5[res]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
arr1=np.arange(1,10).reshape(3,3)

In [53]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2=np.arange(11,20).reshape(3,3)

In [55]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [56]:
np.vstack((arr1,arr2)) #vertical stacking joining 2 arrays

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [57]:
np.hstack((arr1,arr2)) #horizantal stacking joining 2 arrays

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [59]:
#now will arr1 and arr2 change let us check, no right?
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [60]:
#Attributes
#ndim
#size
#itemsize
#shape
#dtype

In [63]:
arr3=np.arange(1,7).reshape(2,3)

In [64]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
print(arr3.ndim)
print(arr3.size)
print(arr3.itemsize)
print(arr3.shape)
print(arr3.dtype)

2
6
4
(2, 3)
int32


In [66]:
#Functions
# 1.Zeroes
# 2.Ones
# 3.Full

In [72]:
arr=np.zeros([3,3],dtype='int32')

In [73]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
arr1=np.ones([3,3],dtype='int32')

In [76]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [77]:
arr2=np.full([2,2],'sathvik')

In [79]:
print(arr2)

[['sathvik' 'sathvik']
 ['sathvik' 'sathvik']]


In [80]:
#eye, it returns the diagonal elements values as 1 and it only allows one positional argument during call which denotes no of
# diagonal values and the size of array
e=np.eye(3,dtype='int32')

In [81]:
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [86]:
#linspace, takes 3 arguments and here the first 2 denote the starting and ending value and the third part decides to how many parts
# the elements will be printed.
arr4=np.linspace(1,10,5) #here 10 will be considered.

In [87]:
arr4

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [100]:
#ravel is the same like flat
arr5=np.arange(1,7).reshape(2,3)
arr5


array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
np.array(arr5.flat)

array([1, 2, 3, 4, 5, 6])

In [121]:
np.array(arr5.ravel())

array([1, 2, 3, 4, 5, 6])

In [106]:
arr5=np.arange(1,7).reshape(2,3)

In [107]:
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr5.min()

1

In [109]:
arr5.max()

6

In [110]:
arr5.sum()

21

In [111]:
arr5.sum(axis=0)

array([5, 7, 9])

In [112]:
arr5.sum(axis=1)

array([ 6, 15])

In [114]:
np.sqrt(arr5)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [115]:
np.mean(arr5)

3.5

In [116]:
np.median(arr5)

3.5

In [118]:
np.std(arr5)

1.707825127659933

In [123]:
a=np.arange(1,5).reshape(2,2)

In [125]:
b=np.arange(6,10).reshape(2,2)

In [126]:
a

array([[1, 2],
       [3, 4]])

In [127]:
b

array([[6, 7],
       [8, 9]])

In [128]:
a+b

array([[ 7,  9],
       [11, 13]])

In [129]:
a-b

array([[-5, -5],
       [-5, -5]])

In [130]:
a*b

array([[ 6, 14],
       [24, 36]])

In [131]:
a/b

array([[0.16666667, 0.28571429],
       [0.375     , 0.44444444]])

In [132]:
#for matrix multiplication use dot()
print(a.dot(b))

[[22 25]
 [50 57]]


In [133]:

c=np.arange(1,10).reshape(3,3)

In [134]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
#transpose
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [136]:
#user defined functions for arrays are done by vectorize
list1=list(range(1,10))

In [150]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [151]:
a=np.array(list1)

In [152]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
f=np.vectorize(lambda x : x/(x+1))

In [154]:
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       ])