In [3]:
#reverse of an array
import numpy as np
arr1=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])

In [4]:
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [6]:
print(arr1[::-1])

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [7]:
#2d array with 1 on border and 0 inside
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#each element in array1 also present in array2
arr2=np.array([0,10,20,40,60])
arr3=np.array([0,40])
np.in1d(arr2,arr3)

array([ True, False, False,  True, False])

In [12]:
#setdiff should return unique sorted order
arr4=np.array([0,10,20,40,60,80])
arr5=np.array([10,30,40,50,70])
np.setdiff1d(arr4,arr5)

array([ 0, 20, 60, 80])

In [13]:
#diagonal equals 4,5,6,8
arr6=np.diagflat([4,5,6,8])

In [14]:
arr6

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])